language: go
go: 1.1

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - go get bitbucket.org/liamstask/goose
  - go get github.com/lib/pq

env:
  - DB=postgres
  - DB=mysql
  # - DB=sqlite

before_script: 
  
  # TODO make use of test specific database values once we refactor out SQLConf design
  - sh -c "if [ '$DB' = 'postgres' ]; then psql --V fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database points;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database points;'; fi"
  - sh -c "goose -path db/$DB -env test status"
  - sh -c "goose -path db/$DB -env test up"
  # - sh -c "if [ '$DB' = 'sqlite' ]; then sqlite3 points; fi"

script: go test