language: go
go: 1.1

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - go get bitbucket.org/liamstask/goose

env:
  - DB=postgres

before_script: 
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database points;' -U postgres; fi"
  - sh -c "goose -path db/$DB -env test up"

script: go test