language: go
go: 1.1

install:
  - go get bitbucket.org/liamstask/goose

env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite

before_script: 
  
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database golang_geo_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database golang_geo_test;'; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then sqlite3 golang_geo_test; fi"
  - sh -c "/home/travis/gopath/bin/goose -path db/$DB -env test up"

script: go test