language: go
go: 1.1

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - go get github.com/erikstmartin/go-testdb  

env:
  - DB=postgres
  - DB=mysql
  - DB=mock

before_script: 
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database points;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database points;'; fi"
  - sh -c "if [ '$DB' != 'mock' ]; then goose -path db/$DB -env test up; fi"

script: go test